### ISSUE TITLE
Failed to import animation using AE plugin

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-web#2643] opened 2021-09-19 04:43 UTC
@bodymovin I'm trying to fix https://github.com/airbnb/lottie-android/issues/1899 on the Android player. However, it is failing to import `thumbs_up_keyframes.json` with this error:
![image](https://user-images.githubusercontent.com/1307745/133915718-acac74b8-c881-4a98-964b-f38e94cf8e7f.png)

**Comment by bodymovin** [comment] 2021-09-27 12:17
It looks like that json file doesn't seem to be compatible with the lottie format. One of its animated properties has an easing curve on its last keyframe, which it shouldn't. That's why it is breaking when imported.
Maybe it has been modified after exporting it with bodymovin.

**Comment by bodymovin** [comment] 2021-09-27 12:30
Ok, I found what the problem is. It seems it was exported converting expressions to keyframes, and apparently, that's when bodymovin is adding easing data when it shouldn't.
I'll fix it for the next build. At the moment, you can manually delete the last in and out easing curve data from the last keyframe and it should work correctly.

**Comment by bodymovin** [comment] 2021-10-12 10:12
fixed on version `5.7.14`

**Closed by bodymovin** 2021-10-12 10:12 UTC
Labels: bug
