### ISSUE TITLE
Cannot read property 'constructor' of undefined when using expressions

### ISSUE THREAD

**Issue by Hargalaten** [airbnb/lottie-web#713] opened 2017-11-09 09:59 UTC
**Tell us about your environment**

* **Browser and Browser Version:** Chrome  61.0.3163.100
* **After Effects Version:** CC2017

**What did you do? Please explain the steps you took before you encountered the problem.**
Only exported the bodymovin
**What did you expect to happen?**
The animation to actually animate
**What actually happened? Please include as much _relevant_ detail as possible.**
The error showing in developers tool is:
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at sub (demo.html:34)
    at Object.eval (eval at initiateExpression (demo.html:10), <anonymous>:4:45)
    at Object.executeExpression [as getValue] (demo.html:34)
    at TextAnimatorProperty.getMeasures (demo.html:27)
    at SVGTextElement.renderLetters (demo.html:29)
    at SVGTextElement.renderFrame (demo.html:29)
    at SVGRenderer.renderFrame (demo.html:28)
    at AnimationItem.renderFrame (demo.html:29)
    at AnimationItem.gotoFrame (demo.html:29)
    at AnimationItem.checkLoaded (demo.html:29)

This export was working on a previous version of bodymovin (4.10) and it's not working on the current release.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[SPINNING.zip](https://github.com/bodymovin/bodymovin/files/1457148/SPINNING.zip)

**Comment by bodymovin** [comment] 2017-11-09 23:51
Found the issue, will be fixed on the next deploy.
Thanks!

**Comment by 18292843691** [comment] 2018-07-23 12:49
i have that now.
I also encountered this problem, after packaging via webpack, Cannot read property 'constructor' . At
```
function $bm_isInstanceOfArray(e) {
         Return e.constructor === Array || e.constructor === Float32Array;
     }
```

**Comment by bodymovin** [comment] 2018-07-23 12:51
@18292843691 Is it only happening when packaging?
can you share the animation?

**Comment by 18292843691** [comment] 2018-07-23 13:03
@bodymovin yes, Only happening when packaging. Anxious to use it.
![](http://or3233yyd.bkt.clouddn.com//18-7-23/30195880.jpg)
![](http://or3233yyd.bkt.clouddn.com//18-7-23/33982160.jpg)

animation like that
![](http://or3233yyd.bkt.clouddn.com//18-7-23/54159149.jpg) how to share you ?

**Comment by bodymovin** [comment] 2018-07-23 13:04
@18292843691 can you share a link where I can check the error?

**Comment by 18292843691** [comment] 2018-07-23 13:53
We temporarily replaced the static image, there is no link at the moment.sorry。

**Closed** 2018-09-30 02:03 UTC

**Comment by bodymovin** [comment] 2018-11-30 13:50
@mateenagy what tooling do you use for building the project?
Also, can you share a link with the error?

**Comment by mateenagy** [comment] 2018-11-30 14:08
I use the angular cli to build the project. I can't share the link where the animation running because of the policy and it also not showing the error in the console only in sentry so I attach the picture of the sentry log if it is okay.
<img width="823" alt="screenshot 2018-11-30 at 15 03 45" src="https://user-images.githubusercontent.com/17217453/49293806-725ebc00-f4b1-11e8-9fe0-74d71842b3ba.png">

**Comment by bodymovin** [comment] 2018-11-30 14:14
Can you share a reduced version that doesn't conflict with policies?
From what I've gathered so far, it seems to be related to a  js minifier / uglifier that messes the code up and removes array references.
But I need more context to try to figure this out.
What I know is that it's definitely related to an expression on some layer property.

**Comment by mateenagy** [comment] 2018-11-30 14:18
Okey I will try to reproduce a blank angular project with this animation only and share it with you.

**Comment by mateenagy** [comment] 2018-11-30 15:35
@bodymovin I reproduce only that complex animation with a blank angular project and it's also working local environment but after I put on my server it throw the error.
Here is the repo with all the codes if pull the repo you can run it on localhost and it will work:
https://github.com/mateenagy/angular-bodymovin
And here is the page on my server with the error (Here you can see in the console):
https://matenagy.me/

**Comment by mateenagy** [comment] 2018-11-30 18:23
@bodymovin I start looking for more complex animation in this repo and try them and all of them works fine. So I started looking at my ae project what can cause the problem and it I start turning off things. Motion blur was turned on for every shape so I turned them off and actually it works, but I found it a little weird that when I run locally it is working just fine with the motion blur turned on.

**Comment by bodymovin** [comment] 2018-11-30 18:30
@mateenagy motion blur shouldn't have anything to do with it, it's probably something else, since motion blur is ignored on export.
It's most likely related to an expression.

**Comment by bodymovin** [comment] 2018-12-03 02:35
@mateenagy I went to that url and there doesn't seem to trigger any error. Dod you make it work or update the animation?

**Comment by mateenagy** [comment] 2018-12-03 10:00
@bodymovin Yes I make it work and you were right. My college made the animation and he use expression which I didn't see first so I think that cause the error, but still don't get it why is it worked when I run it locally and get the error when I build the project. Btw Thanks for the help 😄
