### ISSUE TITLE
Shapes are not rendered correctly in HTML

### ISSUE THREAD

**Issue by adriendurepaire** [airbnb/lottie-web#794] opened 2018-01-02 16:03 UTC
Hi,

I made an animation without camera, rendered in SVG, and everything works fine (tested in Chrome, Firefox and Edge), except track matte in Firefox : https://numeoproduction.fr/dev/bodymovin/bot3.html
I tried to add a camera to experiment a parallax effect, and I noticed different problems in HTML : https://numeoproduction.fr/dev/bodymovin/parallax-bot/parallax-bot.html

- Chrome, Firefox and Edge : Shapes are not rendered correctly, they seem cropped. Also, track matte is not rendered (not essential for this animation)
- Edge : Z-position and layer order are not respected
- Firefox : The animation is blurry

Have you ever encountered these problems ?

Thanks in advance

**Comment by bodymovin** [comment] 2018-01-02 23:24
Hi, using strokes with the html renderer creates this kind of issues, because the actual size of the shape including the stroke is not well reported by the browser.
If you create a rectangle with a transparent fill that covers the size of the shape including the stroke, it should be fixed.

**Comment by Numeo** [comment] 2018-01-03 15:27
Hi @bodymovin ! Perfect, everything is ok now : https://numeoproduction.fr/dev/bodymovin/parallax-bot/parallax-bot.html
In Edge, if you put a micro offset for each layers, the problem is solved. But for the blurry render in Firefox, do you know a way to solve it ? Thanks

**Comment by bodymovin** [comment] 2018-01-03 16:27
I guess it's because of the way Firefox renders textures on the gpu.
Probably, any scaling is done when the layer is already painted, so it is no longer a vector that scales smoothly.

**Closed** 2020-04-05 01:47 UTC
