### ISSUE TITLE
Text is not defined

### ISSUE THREAD

**Issue by gerngesehen** [airbnb/lottie-web#1283] opened 2018-10-05 09:13 UTC
**Tell us about your environment**

* **Browser and Browser Version:** Google Chrome 68
* **After Effects Version:** After Effects 2017 CC

**What did you do? Please explain the steps you took before you encountered the problem.**
I did render an animation for my website as a header. In After Effects there are no errors. Also if I look at my demo.html which was rendered in After Effects it works fine! Implementing it into my website it stops working and the error message is: Uncaught ReferenceError: text is not defined
    at TextProperty.eval (eval at initiateExpression (bodymovin.min.js:10), <anonymous>:2:1)

**Download link to aep:**
https://bldsg-my.sharepoint.com/:u:/g/personal/pascal_eugster_edu_gbssg_ch/EaDQzdsTp_1KhdV6GY_1Ko0Bz5tN9jUYngHU1aqA6v8VUA?e=eNRZKZ

**Comment by bodymovin** [comment] 2018-10-06 13:39
Hi, can you share a link to the implementation?

**Comment by gerngesehen** [comment] 2018-10-07 07:30
Thanks for your quick reply. I wan't to add it in the header at www.gerngesehen.ch.
But it is not live for the moment because im working with git and xampp and i just push something if it works. Here are some screenshots of the implementation.
![image](https://user-images.githubusercontent.com/38924344/46579471-d82f4a00-ca12-11e8-9d0c-40ed82f91e3b.png)
![image](https://user-images.githubusercontent.com/38924344/46579487-4247ef00-ca13-11e8-8b87-9e487fff6bd2.png)

**Comment by vc-raj** [comment] 2022-11-22 13:56
hi

**Comment by kudanai** [comment] 2022-12-01 12:43
Closing this issue for now since it's been a while. Please re-open it if the issue is still relevant to recent versions.

**Closed by kudanai** 2022-12-01 12:43 UTC
