### ISSUE TITLE
Lottie-web is using huge RAM memory for just 30 assets

### ISSUE THREAD

**Issue by madhakumar42** [airbnb/lottie-web#918] opened 2018-03-17 06:35 UTC
Hi,
I am using Lottie-web in my application. I am using 30 assets right now and the RAM memory allocated for them exceeds 1.5GB in chrome. Is there something am doing wrong ?

I have included the heap snapshot and the chrome task manager

![capture](https://user-images.githubusercontent.com/37467313/37552401-7da38dea-29da-11e8-975d-a18ae50d26ef.PNG)

![capture](https://user-images.githubusercontent.com/37467313/37552422-e6fadb54-29da-11e8-8723-74119454ebb1.PNG)

**Comment by bodymovin** [comment] 2018-03-17 12:27
hi, can you share a link to see how you're implementing it?

**Comment by madhakumar42** [comment] 2018-03-19 11:24
Hi, I do not have a working link to provide to you right now , but i will provide a json file which i am using in my application to load assets , you can see that i am going to use more than 60 assets at a time using the library , so i need to ensure that the ram usage is very low so the people using it in low RAM system's wont face an issue
The json which i am providing you is created using bodymovin plugin and when loading 60 of them my ram goes up to 600MB

https://drive.google.com/file/d/1OcJlvVXTXc3B-gG_QYPYi-kixKzDwT_H/view?usp=sharing

**Comment by madhakumar42** [comment] 2018-03-19 13:29
Hi @bodymovin .

Sorry for the delayed response again. Please check the following link. This is how I am implementing it.

https://codesandbox.io/s/xpm9yojj5o

**Comment by bodymovin** [comment] 2019-11-22 21:24
Closing, reopen if necessary

**Closed by bodymovin** 2019-11-22 21:24 UTC

**Comment by dgknca** [comment] 2020-12-17 06:10
> Closing, reopen if necessary

What is the cause of this problem? Is the file too big?

**Comment by alexaaaant** [comment] 2020-12-28 11:55
> Closing, reopen if necessary

Have you solved this problem?

**Comment by chanjungkim** [comment] 2023-01-16 09:59
Have you..?
