### ISSUE TITLE
Can't export images

### ISSUE THREAD

**Issue by uogie** [airbnb/lottie-web#1060] opened 2018-05-25 07:08 UTC
**Tell us about your environment**
Windows 7
* **Browser and Browser Version:**
* **After Effects Version:**
CC2017
**What did you do? Please explain the steps you took before you encountered the problem.**
Tried to export composition with image (png)
**What did you expect to happen?**
Normal export
**What actually happened? Please include as much _relevant_ detail as possible.**
Bodymovin is stuck on exporting image. Image gets rendered in render que and if I try to export only shapes they get exported correctly. But image export hangs (waited 15 hours just to be sure).
Version is 5.1.15.  No previous issues with older versions.

Edit: just noticed that rendered images can be found in \AppData\Local\Temp\Bodymovin.
Bodymovin just displays the rotating icon and exporting image text.

**Comment by bodymovin** [comment] 2018-05-26 15:51
Found the issue.
Will be fixed on the next build.
Probably by tomorrow EOD.

**Comment by uogie** [comment] 2018-05-28 07:45
Great news, thanks!

**Comment by iamthuypham** [comment] 2018-06-05 20:03
Did 'next build' already been release ?
I currently have this issue.

**Comment by bodymovin** [comment] 2018-06-05 20:04
yes
what version of bodymovin are you using in AE?

**Comment by iamthuypham** [comment] 2018-06-05 20:05
5.1.16 @bodymovin

**Comment by bodymovin** [comment] 2018-06-05 20:06
hmm it should work fine
can you share a screenshot of where it is stuck?

**Comment by iamthuypham** [comment] 2018-06-05 20:07
The bodymovin was hanging at `export images`. Then I try clicking Cancel, this is pops up:
![capture](https://user-images.githubusercontent.com/5633434/40999979-6337213a-68c1-11e8-90e2-97f09fbf60e8.PNG)

**Comment by bodymovin** [comment] 2018-06-05 20:09
I see.
Just to confirm, do you have that preference enabled in After Effects?

**Comment by iamthuypham** [comment] 2018-06-05 20:10
I actually newbie AE :P 
I dont see the Preferences tab anywhere. Let me try looking for it

**Comment by iamthuypham** [comment] 2018-06-05 20:11
Hey, it seems working.
Sorry for false alarm.
I should know better

**Comment by bodymovin** [comment] 2018-06-05 20:11
no problem, glad it's working now.

**Closed by bodymovin** 2018-06-05 20:11 UTC

**Comment by richiepu** [comment] 2018-09-11 11:38
sorry, @bodymovin 
I can't export images in bodymovin 

- windows 10
- AE 2018 CC

![image](https://user-images.githubusercontent.com/8892158/45357859-39255700-b5fa-11e8-9f6c-2311a2063a70.png)

**Comment by rahul1918** [comment] 2020-03-14 10:09
Same issue with me also, I m have jpg sequence images and I want to convert in json file. I tried every possible way but it stuck on exporting jpg 0001.. No progress happening at all.

**Comment by bodymovin** [comment] 2020-03-28 14:54
Yes, I'm trying to fix an issue with AE 2018 and images, but it's going to take some time.
If you can, try upgrading to a newer AE version.

**Comment by xuhong** [comment] 2020-05-11 09:02
hi, is there any progress for AE 2018?

**Comment by xuhong** [comment] 2020-05-13 09:38
I found the problem is that local server did't start successfully, exporting images will call `compressImage` function, which will request `http://localhost:3119/processImage/` api and failed, I don't know the reason for now. @bodymovin

**Comment by xuhong** [comment] 2020-05-14 07:30
Finally I figure out the problem, AE2018 node version is 7.7.4, but imagemin package use syntax that require higher version of node, downgrade imagemin version to 6 solve the problem.

**Comment by bodymovin** [comment] 2020-05-23 16:22
@xuhong interesting finding! was this the only library that needed to be downgraded in your test?

**Comment by xuhong** [comment] 2020-05-23 18:12
Yes, only imagemin.

**Comment by jackmorteza** [comment] 2020-11-09 17:38
I can render a comp to Jason with bodymovin but it does not include the images of my comp.
So I can't use it in my app

**Comment by rlo666** [comment] 2022-02-10 03:53
> Finally I figure out the problem, AE2018 node version is 7.7.4, but imagemin package use syntax that require higher version of node, downgrade imagemin version to 6 solve the problem.

sorry an animator using AE 2018 here.
I am currently facing the same issue but I don't understand what imagemin is.
Can you please offer me a steps how can I solve this issue other than switching AE version?
