### ISSUE TITLE
Web Player Embed Not Freezing on Last Frame

### ISSUE THREAD

**Issue by MattDAndre** [airbnb/lottie-web#1648] opened 2019-05-29 02:22 UTC
**Tell us about your environment**

* **Browser and Browser Version:** Latest Chrome
* **After Effects Version:** 15.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**

So, I'm working in Webflow using the Lottie Web Player! I exported my .json file using the "Guides" setting in Bodymovin. I uploaded it to LottieFiles, and used my <script> code from the Web Player in an html embed. The only box I had checked was autoplay, so that it'd play once and freeze.

**What did you expect to happen?** 

The animation showed up on my published website just fine (so cool), but I expected the animation to freeze on it's last frame. Instead it seems to reset to the first frame. 

https://murrvox.webflow.io/

It's all the way at the bottom! 

**What actually happened? Please include as much _relevant_ detail as possible.**

The animation played once all the way through and reset to the first frame.

**Comment by bodymovin** [comment] 2019-05-30 00:45
Hi, how are you implementing the hover behavior?
Is the code somehwhere to check?

**Comment by MattDAndre** [comment] 2019-05-30 00:49
I think the link I shared had it when I was testing the hover feature out, but the goal would be not to use it. I get the same result when using this code:

<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player 
    src="https://assets3.lottiefiles.com/packages/lf20_oNDAX8.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"    autoplay >
</lottie-player>

**Comment by bodymovin** [comment] 2019-05-30 00:52
Can you build a reduced version of the issue? Perhaps using codepen?
I just tried it and couldn't reproduce it.

**Comment by MattDAndre** [comment] 2019-05-30 00:57
Good idea! 

https://codepen.io/MattDAndre/pen/mYzOeb

So, what I'd love to happen is for the animation to, when if finishes, stay at the last frame instead of reverting back to it's first.

**Comment by bodymovin** [comment] 2019-05-30 09:32
It seems that the lottie-player component is intentionally moving to the first frame once the animation is complete: https://github.com/LottieFiles/lottie-player/blob/d7f7d4fb5ed9f6862ab00016855e9a3d7be2e94d/src/main.ts#L223  
I'd suggest that you report this issue on their repo.

**Comment by MattDAndre** [comment] 2019-05-30 14:34
Awesome, will do! Thank you so much for making such an amazing tool and having stellar involvement in your community. Really appreciate it :)

**Closed** 2019-11-21 00:53 UTC
