### ISSUE TITLE
Unable to select comps 

### ISSUE THREAD

**Issue by jimiswells** [airbnb/lottie-web#1764] opened 2019-08-09 13:49 UTC
* MAC OS HIGH SIERRA 

* **After Effects Version:16.1.2**
* **Bodymovin' Version:5.56**

I'm unable to select comps to export, and refreshing bodymovin' panel has no effect. 

I've tried reinstalling both AE and Bodymovin' to no avail...

![Screen Shot 2019-08-09 at 14 46 32](https://user-images.githubusercontent.com/7958596/62783663-c2683680-bab4-11e9-8633-d4b101516ad0.png)

**Comment by bodymovin** [comment] 2019-08-17 16:02
Hi, I can't reproduce the issue.
Is it possible that it is a window height problem? Can you try enlarging the height of the extension?

**Comment by kudanai** [comment] 2022-12-01 12:24
I'm closing this issue as it is quite old. Please re-open if this is still relevant

**Closed by kudanai** 2022-12-01 12:24 UTC
