### ISSUE TITLE
Performance continually decreasing with every call of animation.playSegments()

### ISSUE THREAD

**Issue by Veeeeeeee** [airbnb/lottie-web#754] opened 2017-12-08 15:36 UTC
**Tell us about your environment**
An iMac (OsX 10).

* **Browser and Browser Version:**
I tested it in chrome (62), firefox (57) and safari (11)

* **After Effects Version:**
14.0.0.207

**What did you do? Please explain the steps you took before you encountered the problem.**
**What did you expect to happen?**
**What actually happened? Please include as much _relevant_ detail as possible.**
I'm working on a project where i have to animate a lot between different segments of one animation. To do this i use the playSegments function, always with an array of 2 values [fromFrame, toFrame] and the forced flag set to true.
After a while of testing without reloading i noticed a slight lag, which seemed to get worse the more input i gave.
The performance inspector in chrome confirmed my assumption, that the CPU has to work harder presumably with every call of the playSegments function. According to the performance inspector the browser accumulates "Animation Frame Fired" events. It seems like the animations are stacking up in the background. Am i using something wrong here or is there a way to clear animation data?
Really looking forward to your replies, great project apart from this issue btw! :)

**Comment by bodymovin** [comment] 2017-12-09 23:25
Hi, I tried to reproduce this issue but I can't seem to find the problem.
Do you have an example I can try out?

**Comment by Veeeeeeee** [comment] 2017-12-10 14:26
Hey, thanks for looking into this, i'll upload an example asap :)

**Comment by Veeeeeeee** [comment] 2017-12-13 11:36
Okay, so here is an [example](http://veeee.de/bodymovin/inOutAnimation).

It’s one animation which plays and skips between segments.
Try observing the performance in the beginning, then skip a lot between different parts with the yellow buttons below and measure the performance again. You should notice a decrease.

The project uses react, i attached the sources of the inOutAnimation component and the site where it is embedded (called inOutAnimationTest):
[inOutAnimation.zip](https://github.com/airbnb/lottie-web/files/1555326/inOutAnimation.zip)

If you need any more resources let me know :)

**Comment by bodymovin** [comment] 2017-12-13 12:35
I've managed to reproduce the issue. It's related to setting loop to false and manually looping it on every onComplete event.
When it's fixed I'll let you know.

**Comment by bodymovin** [comment] 2017-12-13 13:24
Fixed! I'll upload it tonight.
Meanwhile, if you want to try it, here's the new build.
[player.zip](https://github.com/airbnb/lottie-web/files/1555606/player.zip)

**Comment by Veeeeeeee** [comment] 2017-12-13 14:17
Well that was quick, great support!
I'll check it out :)

**Comment by Veeeeeeee** [comment] 2017-12-13 14:51
Ok, so i replaced the lottie-files in node_modules/lottie-web/build/player with the ones from the zip and now it can't seem to play segments backwards, is there something i need to change in the code? Also the looped segments look less smooth at the point of looping.

**Comment by bodymovin** [comment] 2017-12-13 16:41
I did an update on version 5.0.5 to be more aligned on how AE does the loops.
Can you share the .aep where you see the loop failing?

**Comment by Veeeeeeee** [comment] 2017-12-13 19:06
Sure, tomorrow i can share it. The looping doesn't fail though, it only feels a bit more choppy than before. The more important problem for our project is that now it's apparently impossible to play segments backwards (startframe > endframe)

**Comment by bodymovin** [comment] 2017-12-13 23:57
I tried playing a segment with start point larger than end point and it seems to be working.
There must be an extra condition.
Can you show me a reduced example?

**Comment by bodymovin** [comment] 2017-12-14 00:04
[player.zip](https://github.com/airbnb/lottie-web/files/1557521/player.zip)
I think I found the issue. Can you try this player?

**Comment by Veeeeeeee** [comment] 2017-12-14 03:43
The performance and the playing backwards seem to be resolved, good stuff!
Only the looping still seems to skip a frame or sth, you can see it easily when you decrease the animation speed.

**Comment by bodymovin** [comment] 2017-12-14 10:36
can you share the .aep of the animation so I can compare?

**Comment by Veeeeeeee** [comment] 2017-12-15 17:50
Sure, i'll share it on monday, when i'm back at the office :)

**Comment by Veeeeeeee** [comment] 2017-12-18 10:44
Here we go, that's the .aep file of the example animation:

[BodyMovinInOut.aep.zip](https://github.com/airbnb/lottie-web/files/1567424/BodyMovinInOut.aep.zip)

**Comment by bodymovin** [comment] 2017-12-18 12:33
Thanks. What are the segments frame numbers you're looping?

**Comment by Veeeeeeee** [comment] 2017-12-18 13:33
5 to 15, 25 to 35, 45 to 65 and 75 to 85

**Comment by bodymovin** [comment] 2017-12-22 14:40
this should be fixed in version 5.0.6

**Comment by Veeeeeeee** [comment] 2017-12-22 16:41
Cool, i'll try it out.

**Closed** 2019-11-22 21:33 UTC

**Comment by Timur00Kh** [comment] 2020-01-31 11:10
Same issue in YaBrowser/20.2.0.1043 specifically (based on Chrome/79.0.3945.117).
Chrome - ok.

**Comment by bodymovin** [comment] 2020-02-01 12:48
@Timur00Kh can you share the animation?
