### ISSUE TITLE
Struggling to get the Script to run in the browser :( 

### ISSUE THREAD

**Issue by HBVIZ** [airbnb/lottie-web#1679] opened 2019-06-17 17:24 UTC
I am having trouble getting the animation to show in Chrome

**### HTML -**

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/stylesheet.css" type="text/css">
    <script type="text/javascript" src="lottie.js"></script>
    <title>fml</title>
</head>

<body>

    <h1>:(</h1>

<div id="lottie"></div>

<script>
    
    var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData,
        path:'data.json'

    };

    var anim;

    anim = lottie.loadAnimation(params);

</script>
</body>
</html>

css - 

body{
    background-color:rgb(7, 7, 7);
    margin: 0px;
    height: 100%;
    overflow: hidden;
}
#lottie{
    background-color:rgb(17, 14, 14);
    width:100%;
    height:100%;
    display:block;
    overflow: hidden;
    transform: translate3d(0,0,0);
    text-align: center;
    opacity: 1;
}

h1 {
 color: aqua;
 font-family: sans-serif;
}

I have tried a few variations and non seem to have worked for me! i am new to writing these languages although just to get my animation to display i seemed to have followed all the steps i can find point to point. 

I do aim to make some animated buttons implementing Sass/scss once i get the basics 

Hopefully someone can help me out here as im really stuck :(

**Comment by bodymovin** [comment] 2019-06-17 17:38
hi, do you have a link with the implementation to check?
There might be several reasons why it is not working.

**Comment by mrocchi** [comment] 2019-06-17 22:31
@bodymovin I'm having the same error, and have tried different ways of export. But even if the json runs in Lottie in doesn't run in the browser. 

Here's the link to one.

https://lottiefiles.com/share/FVbxbi

**Comment by Inventsable** [comment] 2019-06-18 01:52
Hi guys. Just to clarify do you mean that when you use Inspect on your pages, that the element defined as the Lottie instance has no container or contents, or is it simply not displaying? If not displaying, does it have both width and height dimensions?

One common issue I run into at the beginning is noticing that my `SVG` root has a height but no width or vice versa, in which case simple CSS at low specificity on the tag itself can solve this:

```css
svg {
    width: 100%;
}
```

**Comment by mrocchi** [comment] 2019-06-18 03:02
@Inventsable, after I exported the json my devs told me that it doesn't show anything. Basically, it's a blank screen.

I'm using this tool to test the jsons and doesn't load anything. 

https://nicolasjengler.github.io/bodymovins-json-tester/dist/

**Comment by Inventsable** [comment] 2019-06-18 03:25
@mrocchi, that website doesn't work for any Lottie file -- mine or your own:

<img width="498" alt="ice_screenshot_20190617-201249" src="https://user-images.githubusercontent.com/37279677/59650848-5adcdd00-913c-11e9-95cd-456cf3252f55.png">

Have you gotten any file to display with it?

Can you provide your AEP or the files? If the link earlier was the file in question it clearly does work if it's being played by LottieFiles, but I'm not able to do much with only verbal description -- unless you tell me what the contents of the Lottie instance HTML element are via Inspect or DevTools or define the error being thrown in the console, I have no way of knowing if the problem is on the side of Lottie or the way you're implementing them in the browser (missing dimensions, etc.)

**Comment by Inventsable** [comment] 2019-06-18 03:39
@mrocchi See here in [this repl.it](https://repl.it/@Inventsable/Wrench-Loading-Icons) (press run to view):

```
Uncaught TypeError: Cannot read property '0' of undefined
    at l.f [as interpolateValue] (lottie.min.js:1)
    at l.c (lottie.min.js:1)
    at l.u [as getValue] (lottie.min.js:1)
    at GradientProperty.getValue (lottie.min.js:1)
    at new GradientProperty (lottie.min.js:1)
    at SVGGradientStrokeStyleData.SVGGradientFillStyleData.initGradientData (lottie.min.js:1)
    at new SVGGradientStrokeStyleData (lottie.min.js:1)
    at SVGShapeElement.createStyleElement (lottie.min.js:1)
    at SVGShapeElement.searchShapes (lottie.min.js:1)
    at SVGShapeElement.searchShapes (lottie.min.js:1)
```

Your error is being thrown by using an older version of Lottie. In the case of this repl.it, it was initially running the CDN minified version `5.4.3`, when updating to `5.5.3` it does work. In the instance of the website you linked, I suspect they're also using an outdated version which wouldn't support Gradients.

**Comment by Inventsable** [comment] 2019-06-18 03:50
Just as a followup, the [repository to that website is here and it hard codes a version of lottie that has not been updated for over two years](https://github.com/NicolasJEngler/bodymovins-json-tester/tree/master/src/vendor/bodymovin). Since Lottie has progressed quite a bit since then, you won't be able to play any file on that site which isn't two years old! I'd recommend not using that one.

**Comment by Inventsable** [comment] 2019-06-18 04:03
@HBVIZ I bet you have the same issue since you're not using Node. Try replacing this line in your code:

```html
<script type="text/javascript" src="lottie.js">
```

With this:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie.min.js"></script>
```

**Comment by mrocchi** [comment] 2019-06-18 04:03
@Inventsable Thank you for the help. I can share the AE file I'm having problems with. 

I'm using the version 5.5.5 of Bodymovin. 

What did you in order to make that json runs?

**Comment by mrocchi** [comment] 2019-06-18 04:04
This is my AE with the animations. And what I do is simply use Bodymovin (5.5.5) and export the animations. :/ 

[Levels.aep.zip](https://github.com/airbnb/lottie-web/files/3299716/Levels.aep.zip)

**Comment by mrocchi** [comment] 2019-06-18 04:11
I'm really sorry @Inventsable, and I might sound dumb but I have low coding skills. But, how can I update the CDN minified version of bodymovin?

**Comment by Inventsable** [comment] 2019-06-18 04:14
Hi @mrocchi ,

I updated the CDN in my own file, seen in `index.html`:

```html
    <!-- Outdated lottie below was throwing the error -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.4.3/lottie.min.js"></script> -->

    <!-- But it works fine with the latest: -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie.min.js"></script>
```

By grabbing the [most recent CDN](https://cdnjs.com/libraries/bodymovin) link from the README. Just a note, the `v` parameter of the JSON you supplied earlier is at `5.5.1`, I exported from my own `5.5.2` panel and [updated the repl.it with one of the icons from your AEP](https://repl.it/@Inventsable/Wrench-Loading-Icons). Your files are fine, the problem is with your devs using an old version of lottie. Tell them to get off your back and solve their own problems 😉

To update your `<script>`, paste this line at the top of your HTML (or wherever else you're grabbing the `lottie.min.js`, ignore it and use this instead):

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie.min.js"></script>
```

**Comment by mrocchi** [comment] 2019-06-18 04:22
Thank you @Inventsable !! You just saved my life

**Comment by HBVIZ** [comment] 2019-06-18 19:15
> hi, do you have a link with the implementation to check?
> There might be several reasons why it is not working.

Hey @bodymovin !

 Thanks so much for the super fast reply i am really new to this it seems to be working however the images that make up the .Ae file are not syncing with the animation what would be the protocol for attaching the images file created by the Bodymovin plugin with the code? 

 My second question and probably a more silly onet. What would be the best way to present to you my implementation? I am new to Git and i see people using so many different ways to present there projects? 

@Inventsable Thankyou!! i believe that was what the problem was.
@mrocchi Awsome man - :)

**Comment by Inventsable** [comment] 2019-06-19 06:32
@HBVIZ very cool! Glad to hear it displays correctly. Can we close this issue? I'm not sure what the problem would be for your images, but for the sake of keeping problems in places others can easily find them (issue reports with the most relevant titles) I feel it'd be best to move it to a separate issue if need be.

**Comment by HBVIZ** [comment] 2019-06-19 12:15
Yeah sure if you feel that's what is best thanks for the support!

**Closed** 2019-06-19 13:01 UTC
