### ISSUE TITLE
Banner export not working

### ISSUE THREAD

**Issue by rocket-video** [airbnb/lottie-web#1973] opened 2020-02-04 13:21 UTC
Bodymovin 5.6.3  banner export mode generates a folder called banner with a zip file inside.

However, when I open the zip file it shows up empty.

I'm using After Effects 2020 on Windows 10.

**Comment by rocket-video** [comment] 2020-02-04 13:40
Sorry this issue was incorrect

**Comment by rocket-video** [comment] 2020-02-04 13:46
Addtionally, this happens when I upload it to the validator:

![image](https://user-images.githubusercontent.com/60463491/73750271-2c5c5280-475d-11ea-8bd5-c62e0e7b8197.png)

**Comment by rocket-video** [comment] 2020-02-04 14:09
Update: 
If I extract the zip file using 7-zip, and zip the contents again it works in the validator.
The creation of the extra "banner" folder was done by design?
It would make more sense to me if only the zip file got exported from after effects.

**Comment by bodymovin** [comment] 2020-02-08 20:54
Hi, since multiple export options are available, I try to provide a separate folder for each in case more than one is selected.
Regarding the zip, are the files working?

**Comment by rocketluz** [comment] 2020-02-12 07:55
@bodymovin 
The problem persists in version 5.6.4.
When I open the zip file it shows up as empty.

![image](https://user-images.githubusercontent.com/59647231/74314091-2675fb00-4d75-11ea-8afa-7ec7108ac92a.png)

And it returns a 404 on the validator.


The zip file extracts correctly only if I use 7-zip.

Here's the file:
[300x250_map.zip](https://github.com/airbnb/lottie-web/files/4190510/300x250_map.zip)

**Comment by bodymovin** [comment] 2020-02-18 00:53
What validator do you use?

**Comment by bodymovin** [comment] 2020-02-18 01:19
I've been able to reproduce the issue.
It will be fixed on the next release.
Thanks for reporting it!

**Comment by rocketluz** [comment] 2020-02-18 12:54
@bodymovin 
> What validator do you use?
I use https://h5validator.appspot.com/dcm/asset

I noticed another issue with it.

When I remember the settings of one comp and apply them to several comps, they're all exported with the resolution of the comp whose settings I saved, despite having "Use composition size" enabled.

**Closed** 2022-12-02 05:13 UTC
