### ISSUE TITLE
Problems with 3D layers - cutting off from the borders

### ISSUE THREAD

**Issue by Goozoon** [airbnb/lottie-web#1538] opened 2019-03-20 12:00 UTC
Hi all
i have the same problem as it was once described here:
https://github.com/airbnb/lottie-web/issues/561

What could be wrong, please?

Project: https://we.tl/t-gA09CoWs73
IMG: https://pasteboard.co/I6hXYPj.png

**Comment by bodymovin** [comment] 2019-03-20 23:58
Hi, the problem is with how strokes are handled by browsers.
If you add a rectangle with a transparent fill to those layers with a larger surface than the stroke, it should be fixed

**Comment by Goozoon** [comment] 2019-03-21 09:08
Thank you
Indeed. You can also add rectangle and just turn visibility off and it will render as it should

**Comment by Goozoon** [comment] 2019-03-21 14:05
Next problem, 3d rotations are not supported in Lottie for iOS. Animation is stating with no movement :(

**Closed** 2019-05-18 23:03 UTC
